/*
 * Copyright (C) 2016 www.phantombot.net
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* 
 * @author IllusionaryOne
 */

/*
 * customCommandsPanel.js
 * Drives the Custom Commands Panel
 */
(function() {
    var modeIcon = [],
        groupIcons = [],
        disabledCommands = [];

        modeIcon['false'] = "<i style=\"color: #6136b1\" class=\"fa fa-circle-o\" />";
        modeIcon['true'] = "<i style=\"color: #6136b1\" class=\"fa fa-circle\" />";

        groupIcons['0'] = "<i class=\"fa fa-television\" />";
        groupIcons['1'] = "<i class=\"fa fa-laptop\" />";
        groupIcons['2'] = "<i class=\"fa fa-shield\" />";
        groupIcons['3'] = "<i class=\"fa fa-credit-card\" />";
        groupIcons['6'] = "<i class=\"fa fa-clock-o\" />";
        groupIcons['7'] = "<i class=\"fa fa-user\" /></div>";

    /*
     * onMessage
     * This event is generated by the connection (WebSocket) object.
     */
    function onMessage(message) {
        var msgObject;

        try {
            msgObject = JSON.parse(message.data);
        } catch (ex) {
            return;
        }

        // Check for dbkeysresult queries
        if (panelHasQuery(msgObject)) {
            var commandName = "",
                commandValue = "",
                html = "<table>",
                time = "",
                globalCooldown = "",
                globalCooldownTime = "",
                perUserCooldown = "",
                modCooldown = "",
                foundData = false;

            if (panelCheckQuery(msgObject, 'commands_cooldown')) {
                html = "<table>";
                for (idx in msgObject['results']) {
                    commandName = msgObject['results'][idx]['key'];
                    time = msgObject['results'][idx]['value'];

                    if (panelMatch(commandName, 'globalCooldown')) {
                        globalCooldown = msgObject['results'][idx]['value'];
                        continue;
                    }
                    if (panelMatch(commandName, 'globalCooldownTime')) {
                        globalCooldownTime = msgObject['results'][idx]['value'];
                        continue;
                    }
                    if (panelMatch(commandName, 'modCooldown')) {
                        modCooldown = msgObject['results'][idx]['value'];
                        continue;
                    }
                    if (panelMatch(commandName, 'perUserCooldown')) {
                        perUserCooldown  = msgObject['results'][idx]['value'];
                        continue;
                    }

                    foundData = true;
                    html += "<tr class=\"textList\">" +
                            "    <td style=\"width: 15px\">" +
                            "        <div id=\"deleteCooldown_" + commandName + "\" class=\"button\" " +
                            "             onclick=\"$.deleteCooldown('" + commandName + "')\"><i class=\"fa fa-trash\" />" +
                            "    </td>" +
                            "    <td>" + commandName + "</td>" +
                            "    <td>" + time + "</td>" +
                            "</tr>";
                }
                html += "</table>";

                if (!foundData) {
                    html = "<i>No entries in cooldown table.</i>";
                }
                $("#cooldownList").html(html);

                $("#toggleGlobalCooldown").html(modeIcon[globalCooldown]);
                $("#togglePerUserCooldown").html(modeIcon[perUserCooldown]);
                $("#toggleModCooldown").html(modeIcon[modCooldown]);
                $('#globalCooldownTimeInput').attr('placeholder', globalCooldownTime).blur();
            }

            if (panelCheckQuery(msgObject, 'commands_commands')) {
                if (msgObject['results'].length === 0) {
                    $('#customCommandsList').html('<i>There are no custom commands defined.</i>');
                    return;
                }
                for (idx in msgObject['results']) {
                    commandName = msgObject['results'][idx]['key'];
                    commandValue = msgObject['results'][idx]['value'];
                    html += "<tr class=\"textList\">" +
                            "    <td padding=\"5px\">" +
                            "        <div id=\"deleteCommand_" + commandName + "\" class=\"button\" " +
                            "             onclick=\"$.deleteCommand('" + commandName + "')\"><i class=\"fa fa-trash\" />" +
                            "        </div>" +
                            "    </td>" +
                            "    <td><strong>" + commandName + "</strong></td>" +
                            "    <td>" + commandValue + "</td>" +
                            "</tr>";
                }
                html += "</table>";
                $("#customCommandsList").html(html);
            }

            if (panelCheckQuery(msgObject, 'commands_aliases')) {
                if (msgObject['results'].length === 0) {
                    $('#aliasCommandsList').html('<i>There are no aliased commands defined.</i>');
                    return;
                }
                for (idx in msgObject['results']) {
                    commandName = msgObject['results'][idx]['key'];
                    commandValue = msgObject['results'][idx]['value'];
                    html += "<tr class=\"textList\">" +
                            "    <td padding=\"5px\">" +
                            "        <div id=\"deleteAlias_" + commandName + "\" class=\"button\" " +
                            "             onclick=\"$.deleteAlias('" + commandName + "')\"><i class=\"fa fa-trash\" />" +
                            "        </div>" +
                            "    </td>" +
                            "    <td><strong>" + commandName + "</strong></td>" +
                            "    <td>" + commandValue + "</td>" +
                            "</tr>";
                }
                html += "</table>";
                $("#aliasCommandsList").html(html);
            }

            if (panelCheckQuery(msgObject, 'commands_pricecom')) {
                if (msgObject['results'].length === 0) {
                    $('#priceCommandsList').html('<i>There are no commands with prices defined.</i>');
                    return;
                }
                for (idx in msgObject['results']) {
                    commandName = msgObject['results'][idx]['key'];
                    commandValue = msgObject['results'][idx]['value'];
                    html += "<tr class=\"textList\">" +
                            "<td style=\"vertical-align: middle\"><strong>" + commandName + "</strong></td>" +
                            "<td style=\"vertical-align: middle\">" + commandValue + "</td>" +
                            "<td style=\"vertical-align: middle\">" +
                            "    <form onkeypress=\"return event.keyCode != 13\">" +
                            "        <input type=\"number\" min=\"0\" id=\"inlineCommandPrice_"+commandName+"\" placeholder=\"new_price\" />" +
                            "        <button type=\"button\" class=\"btn btn-default btn-xs\"" +
                            "                onclick=\"$.updateCommandPrice('" + commandName + "')\"><i class=\"fa fa-pencil\" /></button>" +
                            "    </form>" +
                            "</td>" +
                            "</tr>";
                }
                html += "</table>";
                $("#priceCommandsList").html(html);
                handleInputFocus();
            }

            if (panelCheckQuery(msgObject, 'commands_disabled')) {
                disabledCommands = [];
                for (idx in msgObject['results']) {
                    disabledCommands[msgObject['results'][idx]['key']] = true;
                }
                sendDBKeys("commands_permcom", "permcom");
            }

            if (panelCheckQuery(msgObject, 'commands_permcom')) {
                var commandTableData = msgObject['results'];
                commandTableData.sort(sortCommandTable);

                for (idx in commandTableData) {
                    commandName = commandTableData[idx]['key'];
                    commandValue = commandTableData[idx]['value'];
                    html += "<tr class=\"textList\">" +
                            "<td><strong>" + commandName + "</strong></td>";

                    if (commandName.indexOf(' ') === -1) {
                        if (disabledCommands[commandName] !== undefined) {
                            html +=  "<td><div id=\"commandEnabled_" + commandName + "\"" +
                                     "         data-toggle=\"tooltip\" title=\"Enable Command\" class=\"button\" onclick=\"$.commandEnable('" + commandName + "', 'enable');\">" +
                                     "    <i style=\"color: #6136b1\" class=\"fa fa-toggle-off\" /></div></td>";
                        } else {
                            html +=  "<td><div id=\"commandEnabled_" + commandName + "\"" +
                                     "         data-toggle=\"tooltip\" title=\"Disable Command\" class=\"button\" onclick=\"$.commandEnable('" + commandName + "', 'disable');\">" +
                                     "    <i style=\"color: #6136b1\" class=\"fa fa-toggle-on\" /></div></td>";
                        }
                    } else {
                        html += "<td />";
                    }

                    html += "<td /><td><div id=\"commandsList_" + commandName + "\"><strong><font style=\"color: #6136b1\">" + groupIcons[commandValue] + 
                            "    </font></strong></div></td>" +

                            "<td><div data-toggle=\"tooltip\" title=\"Set Caster\" class=\"button\" onclick=\"$.commandPermission('" + commandName + "', 0);\">" +
                            "    <i class=\"fa fa-television\" /></div></td>" +

                            "<td><div data-toggle=\"tooltip\" title=\"Set Admin\" class=\"button\" onclick=\"$.commandPermission('" + commandName + "', 1);\">" +
                            "    <i class=\"fa fa-laptop\" /></div></td>" +

                            "<td><div data-toggle=\"tooltip\" title=\"Set Mod\" class=\"button\" onclick=\"$.commandPermission('" + commandName + "', 2);\">" +
                            "    <i class=\"fa fa-shield\" /></div></td>" +

                            "<td><div data-toggle=\"tooltip\" title=\"Set Sub\" class=\"button\" onclick=\"$.commandPermission('" + commandName + "', 3);\">" +
                            "    <i class=\"fa fa-credit-card\" /></div></td>" +

                            "<td><div data-toggle=\"tooltip\" title=\"Set Regular\" class=\"button\" onclick=\"$.commandPermission('" + commandName + "', 6);\">" +
                            "    <i class=\"fa fa-clock-o\" /></div></td>" +

                            "<td><div data-toggle=\"tooltip\" title=\"Set Viewer\" class=\"button\" onclick=\"$.commandPermission('" + commandName + "', 7);\">" +
                            "    <i class=\"fa fa-user\" /></div></td>" +

                            "</tr>";
                }
                html += "</table>";
                $("#permCommandsList").html(html);
                $('[data-toggle="tooltip"]').tooltip();
            }
        }
    }

    /**
     * @function doQuery
     */
    function doQuery() {
        sendDBKeys("commands_commands", "command");
        sendDBKeys("commands_aliases", "aliases");
        sendDBKeys("commands_pricecom", "pricecom");
        sendDBKeys("commands_cooldown", "cooldown");
        sendDBKeys('commands_disabled', 'disabledCommands');
    }

    /**
     * @function sortCommandTable
     * @param {Object} a
     * @param {Object} b
     */
    function sortCommandTable(a, b) {
        return panelStrcmp(a.key, b.key);
    }

    /** 
     * @function deleteCommand
     * @param {String} command
     */
    function deleteCommand(command) {
        $("#deleteCommand_" + command).html("<i style=\"color: #6136b1\" class=\"fa fa-spinner fa-spin\" />");
        // sendDBDelete("commands_delcom_" + command, "command", command);
        sendCommand("delcom " + command);
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }

    /**
     * @function addCustomCommand
     */
    function addCustomCommand() {
        var value = $("#addCommandInput").val();
        if (value.length == 0) {
            $("#addCommandInput").val("Please enter a value");
            setTimeout(function() { $("#addCommandInput").val(""); }, TIMEOUT_WAIT_TIME);
        } else {
            sendCommand("addcom " + $("#addCommandInput").val());
            $("#addCommandInput").val("Submitted");
            setTimeout(function() { $("#addCommandInput").val(""); }, TIMEOUT_WAIT_TIME);
            doQuery();
        }
    }

    /**
     * @function editCustomCommand
     */
    function editCustomCommand() {
        sendCommand("editcom " + $("#editCommandInput").val());
        $("#editCommandInput").val("Submitted");
        setTimeout(function() { $("#editCommandInput").val(""); }, TIMEOUT_WAIT_TIME);
        doQuery();
    }

    /** 
     * @function aliasCommand
     */
    function aliasCommand() {
        sendCommand("aliascom " + $("#aliasCommandInput").val());
        $("#aliasCommandInput").val("Submitted");
        setTimeout(function() { $("#aliasCommandInput").val(""); }, TIMEOUT_WAIT_TIME);
        doQuery();
    }

    /**
     * @function deleteAlias
     * @param {String} command
     */
    function deleteAlias(command) {
        $("#deleteAlias_" + command).html("<i style=\"color: #6136b1\" class=\"fa fa-spinner fa-spin\" />");
        // sendDBDelete("commands_delalias_" + command, "aliases", command);
        sendCommand("delalias " + command);
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }

    /**
     * @function commandPermission
     */
    function commandPermission(command, group) {
        $("#commandsList_" + command).html("<i style=\"color: #6136b1\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("permcom " + command + " " + group);
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }

    /**
     * @function setCommandPrice
     */
    function setCommandPrice() {
        sendCommand("pricecom " + $("#setCommandPriceInput").val());
        $("#setCommandPriceInput").val("Submitted");
        setTimeout(function() { $("#setCommandPriceInput").val(""); }, TIMEOUT_WAIT_TIME);
        doQuery();
    }

    /**
     * @function updateCommandPrice
     */
    function updateCommandPrice(command) {
        sendCommand("pricecom " + command + " " + $("#inlineCommandPrice_" + command).val());
        setTimeout(function() { $("#inlineCommandPrice_" + command).val(""); }, TIMEOUT_WAIT_TIME);
        doQuery();
    }

    /**
     * @function toggleGlobalCooldown
     */
    function toggleGlobalCooldown() {
        $("#toggleGlobalCooldown").html("<i style=\"color: #6136b1\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("toggleglobalcooldown");
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }

    /**
     * @function toggleModCooldown
     */
    function toggleModCooldown() {
        $("#toggleModCooldown").html("<i style=\"color: #6136b1\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("togglemodcooldown");
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }

    /**
     * @function togglePerUserCooldown
     */
    function togglePerUserCooldown() {
        $("#togglePerUserCooldown").html("<i style=\"color: #6136b1\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("toggleperusercooldown");
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }


    /**
     * @function setGlobalCooldownTime
     */
    function setGlobalCooldownTime() {
        var newValue = $("#globalCooldownTimeInput").val();
        if (newValue.length > 0) {
            sendCommand("globalcooldowntime " + newValue);
            $("#globalCooldownTimeInput").val('');
            $("#globalCooldownTimeInput").attr('placeholder', newValue).blur();
        }
    }

    /**
     * @function deleteCooldown
     * @param {String} command
     */
    function deleteCooldown(command) {
        $("#deleteCooldown_" + command).html("<i style=\"color: #6136b1\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("cooldown " + command + " -1");
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }

    /**
     * @function addCooldown
     */
    function addCooldown() {
        var input = $("#cooldownCmdInput").val();
        if (input.length > 0) {
            sendCommand("cooldown " + input);
            $("#cooldownCmdInput").val("Submitted");
            setTimeout(function() { $("#cooldownCmdInput").val(""); doQuery(); }, TIMEOUT_WAIT_TIME);
        }
    }

    /**
     * @function commandEnable
     * @param {String} commandName
     * @param {String} action
     */
    function commandEnable(commandName, action) {
        if (panelMatch(action, 'enable')) {
            $('#commandEnabled_' + commandName).html('<i style="color: #333333" class="fa fa-toggle-on" />');
            sendDBDelete('commands_enablecom', 'disabledCommands', commandName);
        } else {
            $('#commandEnabled_' + commandName).html('<i style="color: #333333" class="fa fa-toggle-off" />');
            sendDBUpdate('commands_enablecom', 'disabledCommands', commandName, 'true');
        }
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }

    // Import the HTML file for this panel.
    $("#commandsPanel").load("/panel/commands.html");

    // Load the DB items for this panel, wait to ensure that we are connected.
    var interval = setInterval(function() {
        if (isConnected && TABS_INITIALIZED) {
            var active = $("#tabs").tabs("option", "active");
            if (active == 1) {
                doQuery();
                clearInterval(interval); 
            }
        }
    }, INITIAL_WAIT_TIME);

    // Query the DB every 30 seconds for updates.
    setInterval(function() {
        var active = $("#tabs").tabs("option", "active");
        if (active == 1 && isConnected && !isInputFocus()) {
            newPanelAlert('Refreshing Commands Data', 'success', 1000);
            doQuery();
        }
    }, 3e4);

    // Export functions - Needed when calling from HTML.
    $.commandsOnMessage = onMessage;
    $.deleteCommand = deleteCommand;
    $.addCustomCommand = addCustomCommand;
    $.editCustomCommand = editCustomCommand;
    $.aliasCommand = aliasCommand;
    $.deleteAlias = deleteAlias;
    $.commandPermission = commandPermission;
    $.setCommandPrice = setCommandPrice;
    $.updateCommandPrice = updateCommandPrice;
    $.addCooldown = addCooldown;
    $.deleteCooldown = deleteCooldown;
    $.toggleGlobalCooldown = toggleGlobalCooldown;
    $.toggleModCooldown = toggleModCooldown;
    $.togglePerUserCooldown = togglePerUserCooldown;
    $.setGlobalCooldownTime = setGlobalCooldownTime;
    $.commandEnable = commandEnable;
})();
