/*
 * cooldownPanel.js
 * Drives the Cooldown Panel
 */
(function() {

    var toggleIcon = [];
        toggleIcon['false'] = "<i class=\"fa fa-circle-o\" />";
        toggleIcon['true'] = "<i class=\"fa fa-circle\" />";

    /*
     * onMessage
     * This event is generated by the connection (WebSocket) object.
     */
    function onMessage(message) {
        try {
            var msgObject = JSON.parse(message.data);
        } catch (ex) {
            return;
        }

        // Check for dbkeysresult queries
        if (msgObject['dbkeysresult'] != undefined) {
            var command = "",
                time = "",
                globalCooldown = "",
                globalCooldownTime = "",
                modCooldown = "",
                html = "",
                foundData = false;

            if (msgObject['dbkeysresult'].localeCompare('cooldown_cooldowns') == 0) {
                html = "<table>";
                for (idx in msgObject['results']) {
                    command = msgObject['results'][idx]['key'];
                    time = msgObject['results'][idx]['value'];

                    if (command.localeCompare('globalCooldown') == 0) {
                        globalCooldown = msgObject['results'][idx]['value'];
                        continue;
                    }
                    if (command.localeCompare('globalCooldownTime') == 0) {
                        globalCooldownTime = msgObject['results'][idx]['value'];
                        continue;
                    }
                    if (command.localeCompare('modCooldown') == 0) {
                        modCooldown = msgObject['results'][idx]['value'];
                        continue;
                    }

                    foundData = true;
                    html += "<tr class=\"textList\">" +
                            "    <td style=\"width: 15px\">" +
                            "        <div id=\"deleteCooldown_" + command + "\" class=\"button\" " +
                            "             onclick=\"$.deleteCooldown('" + command + "')\"><i class=\"fa fa-trash\" />" +
                            "    </td>" + 
                            "    <td>" + command + "</td>" +
                            "    <td>" + time + "</td>" +
                            "</tr>";
                }
                html += "</table>";

                if (!foundData) {
                    html = "<i>No entries in cooldown table.</i>";
                }
                $("#cooldownList").html(html);
    
                $("#toggleGlobalCooldown").html(toggleIcon[globalCooldown]);
                $("#toggleModCooldown").html(toggleIcon[modCooldown]);
            }
        }
    }

    /**
     * @function doQuery
     */
    function doQuery() {
        sendDBKeys("cooldown_cooldowns", "cooldown");
    }

    /**
     * @function toggleGlobalCooldown
     */
    function toggleGlobalCooldown() {
        $("#toggleGlobalCooldown").html("<i style=\"color: blue\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("toggleglobalcooldown");
        setTimeout(function() { doQuery(); }, 500);
    }

    /**
     * @function toggleModCooldown
     */
    function toggleModCooldown() {
        $("#toggleModCooldown").html("<i style=\"color: blue\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("togglemodcooldown");
        setTimeout(function() { doQuery(); }, 500);
    }

    /**
     * @function setGlobalCooldownTime
     */
    function setGlobalCooldownTime() {
        var newValue = $("#globalCooldownTimeInput").val();
        if (newValue.length > 0) {
            sendCommand("globalcooldown " + newValue);
            $("#globalCooldownTimeInput").val('');
            $("#globalCooldownTimeInput").attr('placeholder', newValue).blur();
        }
    }

    /**
     * @function deleteCooldown
     * @param {String} command
     */
    function deleteCooldown(command) {
        $("#deleteCooldown_" + command).html("<i style=\"color: blue\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("cooldown " + command + " -1");
        setTimeout(function() { doQuery(); }, 500);
    }

    /**
     * @function addCooldown
     */
    function addCooldown() {
        var input = $("#cooldownCmdInput").val();
        if (input.length > 0) {
            sendCommand("cooldown " + input);
            $("#cooldownCmdInput").val("Submitted");
            setTimeout(function() { $("#cooldownCmdInput").val(""); doQuery(); }, 1000);
        }
    }

    // Import the HTML file for this panel.
    $("#cooldownPanel").load("/panel/cooldown.html");

    // Load the DB items for this panel, wait to ensure that we are connected.
    var interval = setInterval(function() {
        if (isConnected) {
            doQuery();
            clearInterval(interval); 
        }
    }, 1000);

    // Query the DB every 30 seconds for updates.
    setInterval(function() {
        var active = $("#tabs").tabs("option", "active");
        if (active == 1 && isConnected) {
            newPanelAlert('Refreshing Cooldown Data', 'success', 1000);
            doQuery();
        }
    }, 3e4);

    // Export functions - Needed when calling from HTML.
    $.cooldownOnMessage = onMessage;
    $.addCooldown = addCooldown;
    $.deleteCooldown = deleteCooldown;
    $.toggleGlobalCooldown = toggleGlobalCooldown;
    $.toggleModCooldown = toggleModCooldown;
    $.setGlobalCooldownTime = setGlobalCooldownTime;
})();
