/*
 * helpPanel.js
 * Drives the Help
 */
(function() {

    /*
     * onMessage
     * This event is generated by the connection (WebSocket) object.
     */
    function onMessage(message) {
        var msgObject;

        try {
            msgObject = JSON.parse(message.data);
        } catch (ex) {
            return;
        }

        // Check for dbkeysresult queries
        if (msgObject['versionresult'] != undefined) {
            var version = "";

            if (msgObject['versionresult'].localeCompare('help_version') == 0) {
                version = msgObject['version'];
            } else {
                version = "PhantomBot 2";
            }
            $("#botVersion").html("<strong>" + version + "</strong>");
        }
    }

    // Import the HTML file for this panel.
    $("#helpPanel").load("/panel/help.html");

    // Request the version from the bot. This is only done once.
    var interval = setInterval(function() {
        if (isConnected) {
            requestVersion("help_version");
            clearInterval(interval); 
        }
    }, 200);

    // Export functions - Needed when calling from HTML
    $.helpOnMessage = onMessage;
})();
