/*
 * loggingPanel.js
 * Drives the Logging Panel
 */
(function() {

    var loggingMode = false,
        modeIcon = [];
        modeIcon['false'] = "<i style=\"color: blue\" class=\"fa fa-circle-o\" />";
        modeIcon['true'] = "<i style=\"color: blue\" class=\"fa fa-circle\" />";

    /*
     * onMessage
     * This event is generated by the connection (WebSocket) object.
     */
    function onMessage(message) {
        var msgObject;

        try {
            msgObject = JSON.parse(message.data);
        } catch (ex) {
            return;
        }

        // Check for dbkeysresult queries
        if (msgObject['dbqueryresult'] != undefined) {
            var mode;
            if (msgObject['dbqueryresult'].localeCompare('logging_mode') == 0) {
                loggingMode = (msgObject['result']['loggingEnabled'].localeCompare('true') == 0);
                $("#loggingMode").html(modeIcon[loggingMode]);
            }
        }
    }

    /**
     * @function doQuery
     */
    function doQuery() {
        sendDBQuery("logging_mode", "settings", "loggingEnabled");
    }

    /**
     * @function changeLoggingStatus
     * @param {String} mode
     */
    function changeLoggingStatus(mode) {
        $("#loggingMode").html("<i style=\"color: blue\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("log " + mode);
        setTimeout(function() { doQuery(); }, 500);
    }

    // Import the HTML file for this panel.
    $("#loggingPanel").load("/panel/logging.html");

    // Load the DB items for this panel, wait to ensure that we are connected.
    var interval = setInterval(function() {
        var active = $("#tabs").tabs("option", "active");
        if (active == 5 && isConnected) {
            doQuery();
            clearInterval(interval); 
        }
    }, 200);

    // Query the DB every 30 seconds for updates.
    setInterval(function() {
        var active = $("#tabs").tabs("option", "active");
        if (active == 5 && isConnected) {
            newPanelAlert('Refreshing Logging Data', 'success', 1000);
            doQuery();
        }
    }, 3e4);

    // Export functions - Needed when calling from HTML.
    $.loggingOnMessage = onMessage;
    $.changeLoggingStatus = changeLoggingStatus;
})();
