/*
 * modulesPanel.js
 * Drives the Modules Panel
 */
(function() {

    /*
     * onMessage
     * This event is generated by the connection (WebSocket) object.
     */
    function onMessage(message) {
        try {
            var msgObject = JSON.parse(message.data);
        } catch (ex) {
            return;
        }

        // Check for dbkeysresult queries
        if (msgObject['dbkeysresult'] != undefined) {
            var module = "",
                moduleEnabled = "",
                html = "<table>",
                pill = "";

            if (msgObject['dbkeysresult'].localeCompare('modules_modules') == 0) {
                for (idx in msgObject['results']) {
                    module = msgObject['results'][idx]['key'];
                    moduleEnabled = msgObject['results'][idx]['value'];
                    if (module.indexOf('/core/') === -1 && module.indexOf('/lang/') === -1) {
                        if (moduleEnabled.localeCompare('true') == 0) {
                            pill = "<span class=\"greenPill-sm\">Enabled&nbsp;</span>";
                        } else {
                            pill = "<span class=\"redPill-sm\">Disabled</span>";
                        }
                        html += "<tr><td><div class=\"textList\" style=\"padding: 2px\">" + pill +
                                "</td><td>" + module + "</div></td>" +
                                "<td><button type=\"button\" class=\"btn btn-success btn-xs pull-right\" onclick=\"$.enableModule('" + module + "')\">Enable</button></td>" +
                                "<td><button type=\"button\" class=\"btn btn-danger btn-xs pull-right\" onclick=\"$.disableModule('" + module + "')\">Disable</button></td>" +
                                "</tr>";
                    }
                }
                html += "</table>";
                $("#modulesList").html(html);
            }
        }
    }

    /**
     * @function doQuery
     */
    function doQuery() {
        sendDBKeys("modules_modules", "modules");
    }

    /** 
     * @function enableModule
     * @param {String} module
     */
    function enableModule(module) {
        sendCommand("module enable " + module);
        setTimeout(function() { doQuery(); }, 1000);
    }

    /**
     * @function disableModule
     * @param {String} module
     */
    function disableModule(module) {
        sendCommand("module disable " + module);
        setTimeout(function() { doQuery(); }, 1000);
    }

    // Import the HTML file for this panel.
    $("#modulesPanel").load("/panel/modules.html");

    // Load the DB items for this panel, wait to ensure that we are connected.
    var interval = setInterval(function() {
        if (isConnected) {
            doQuery();
            clearInterval(interval); 
        }
    }, 1000);

    // Query the DB every 30 seconds for updates.
    setInterval(function() {
        if (isConnected) {
            newPanelAlert('Refreshing Data', 'success', 500);
            doQuery();
        }
    }, 3e4);

    // Export functions - Needed when calling from HTML.
    $.modulesOnMessage = onMessage;
    $.enableModule = enableModule;
    $.disableModule = disableModule;
})();
