// Configuration for WebPanel
// Automatically Generated by PhantomBot Core at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelPort = 27004;
var channelName = "notillusionaryone";
var auth="Hbep4vDOwvxc0WgvMjguU0kRpRWJX3";
function getPanelPort() { return panelPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
