// Configuration for WebPanel
// Automatically Generated by PhantomBot Core at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelSettings = {
    panelPort   : 27004,
    channelName : "notillusionaryone",
    auth        : "Hbep4vDOwvxc0WgvMjguU0kRpRWJX3"
};

function getPanelPort() { return panelSettings.panelPort; }
function getChannelName() { return panelSettings.channelName; }
function getAuth() { return panelSettings.auth; }
