// Configuration for YTPlayer
// Automatically Generated by PhantomBot Core at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 25003;
var channelName = "";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
