/*
 * Copyright (C) 2016 www.phantombot.net
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* 
 * @author IllusionaryOne
 */

/*
 * timePanel.js
 * Drives the Time Panel
 */
(function() {

    var sortType = 'alpha_asc',
        modeIcon = [];
        modeIcon['false'] = "<i class=\"fa fa-circle-o\" />";
        modeIcon['true'] = "<i class=\"fa fa-circle\" />";

    /*
     * onMessage
     * This event is generated by the connection (WebSocket) object.
     */
    function onMessage(message) {
        var msgObject,
            timezone = "GMT"; // Default time zone in Core if none given.

        try {
            msgObject = JSON.parse(message.data);
        } catch (ex) {
            return;
        }

        if (msgObject['dbqueryresult'] != undefined) {
            if (msgObject['dbqueryresult'].localeCompare('time_timezone') == 0) {
                if (msgObject['result']['timezone'] != undefined) {
                    timezone = msgObject['result']['timezone'];
                }
                $("#setTimeZoneInput").attr("placeholder", timezone).blur();
            }
        }

        if (msgObject['dbkeysresult'] != undefined) {
            if (msgObject['dbkeysresult'].localeCompare('time_settings') == 0) {
                for (idx in msgObject['results']) {
                    var key = "",
                        value = "";
    
                    key = msgObject['results'][idx]['key'];
                    value = msgObject['results'][idx]['value'];
    
                    if (key.localeCompare('timePromoteHours') == 0) {
                        $("#setTimePromotionInput").attr("placeholder", value).blur();
                    } else {
                        $("#" + key).html(modeIcon[value]);
                    }
                }
            }

            if (msgObject['dbkeysresult'].localeCompare('time_timetable') == 0) {
                var timeTableData = msgObject['results'],
                    username = "",
                    timeValue = "",
                    hrsValue = "",
                    html = "";

                if (sortType.localeCompare('time_asc') == 0) {
                    timeTableData.sort(sortTimeTable_time_asc);
                } else if (sortType.localeCompare('time_desc') == 0) {
                    timeTableData.sort(sortTimeTable_time_desc);
                } else if (sortType.localeCompare('alpha_asc') == 0) {
                    timeTableData.sort(sortTimeTable_alpha_asc);
                } else if (sortType.localeCompare('alpha_desc') == 0) {
                    timeTableData.sort(sortTimeTable_alpha_desc);
                }

                html = "<table>";
                for (var idx = 0; idx < timeTableData.length; idx++) {
                    username = timeTableData[idx]['key'];
                    timeValue = timeTableData[idx]['value'];
                    hrsValue = "(" + Math.floor(timeValue / 3600) + " hrs)";
                    html += "<tr class=\"textList\">" +
                            "    <td style=\"vertical-align: middle; width: 50%\">" + username + "</td>" +
                            "    <td style=\"vertical-align: middle; width: 25%\">" + timeValue + " " + hrsValue +"</td>" +
                            "    <td style=\"vertical-align: middle: width: 25%\">" +
                            "    <form onkeypress=\"return event.keyCode != 13\">" +
                            "        <input type=\"number\" min=\"0\" id=\"inlineUserTime_" + username + "\"" +
                            "               placeholder=\"" + timeValue + "\" value=\"" + timeValue + "\"" +
                            "               style=\"width: 8em\"/>" +
                            "        <button type=\"button\" class=\"btn btn-default btn-xs\" onclick=\"$.updateUserTime('" + username + "')\"><i class=\"fa fa-pencil\" /></button>" +
                            "    </form>" +
                            "</tr>";
                }
                html += "</table>";
                $("#userTimeTable").html(html);
            }
        }
    }

    /**
     * @function doQuery
     */
    function doQuery() {
        sendDBQuery("time_timezone", "settings", "timezone");
        sendDBKeys("time_settings", "timeSettings");
        sendDBKeys("time_timetable", "time");
    }

    /**
     * @function updateUserTime
     * @param {String} username
     */
    function updateUserTime(username) {
        var timeValue = $("#inlineUserTime_" + username).val();
        if (timeValue.length > 0) {
            $("#inlineUserTime_" + username).val('')
            sendDBUpdate("time_timetableUpdate", "time", username, timeValue);
            setTimeout(function() { doQuery(); }, 500);
        }
    }

    /**
     * @function sortTimeTable
     * @param {Object} a
     * @param {Object} b
     */
    function sortTimeTable_alpha_desc(a, b) {
        var keyA = a['key'],
            keyB = b['key'];
        return keyB.localeCompare(keyA);
    }
    function sortTimeTable_alpha_asc(a, b) {
        var keyA = a['key'],
            keyB = b['key'];
        return keyA.localeCompare(keyB);
    }
    function sortTimeTable_time_asc(a, b) {
        var valA = a['value'],
            valB = b['value'];
        return parseInt(valA) - parseInt(valB);
    }
    function sortTimeTable_time_desc(a, b) {
        var valA = a['value'],
            valB = b['value'];
        return parseInt(valB) - parseInt(valA);
    }

    /**
     * @function toggleTimeMode
     * @param {String} divId
     * @param {String} setting
     */
    function toggleTimeMode(divId, setting) {
        $("#" + divId).html("<i style=\"color: blue\" class=\"fa fa-spinner fa-spin\" />");
        sendCommand("time " + setting);
        setTimeout(function() { doQuery(); }, 500);
    }

    /**
     * @function setTimePromotion
     */
    function setTimePromotion() {
        var newTimePromotion = $("#setTimePromotionInput").val();
        if (newTimePromotion.length > 0) {
            sendCommand("time promotehours " + newTimePromotion);
            $("#setTimePromtionInput").val('');
            $("#setTimePromotionInput").attr("placeholder", "Submitting").blur();
            setTimeout(function() { doQuery(); }, 500);
        }
    }

    /**
     * @function setTimeZone
     */
    function setTimeZone() {
        var newTimeZone = $("#setTimeZoneInput").val();
        if (newTimeZone.length > 0) {
            sendCommand("timezone " + newTimeZone);
            $("#setTimeZoneInput").val('');
            $("#setTimeZoneInput").attr("placeholder", "Submitting").blur();
            setTimeout(function() { doQuery(); }, 500);
        }
    }

    /**
     * @function modifyUserTime
     * @param {String} action
     */
    function modifyUserTime(action) {
        var username = $("#adjustUserTimeNameInput").val(),
            timeAdjust = $("#adjustUserTimeSecsInput").val();

        if (username.length > 0 && timeAdjust.length > 0) {
            sendCommand("time " + action + " "  + username + " " + timeAdjust);
            $("#adjustUserTimeNameInput").val('');
            $("#adjustUserTimeSecsInput").val('');
            setTimeout(function() { doQuery(); }, 500);
        }
    }

    /**
     * @function setTimeSort
     * @param {String} type
     */
    function setTimeSort(type) {
        sortType = type;
        doQuery();
    }

    // Import the HTML file for this panel.
    $("#timePanel").load("/panel/time.html");

    // Load the DB items for this panel, wait to ensure that we are connected.
    var interval = setInterval(function() {
        var active = $("#tabs").tabs("option", "active");
        if (active == 6 && isConnected) {
            doQuery();
            clearInterval(interval); 
        }
    }, 200);

    // Query the DB every 30 seconds for updates.
    setInterval(function() {
        var active = $("#tabs").tabs("option", "active");
        if (active == 6 && isConnected) {
            newPanelAlert('Refreshing Time Data', 'success', 1000);
            doQuery();
        }
    }, 3e4);

    // Export functions - Needed when calling from HTML.
    $.timeOnMessage = onMessage;
    $.toggleTimeMode = toggleTimeMode;
    $.setTimePromotion = setTimePromotion;
    $.setTimeZone = setTimeZone;
    $.modifyUserTime = modifyUserTime;
    $.updateUserTime = updateUserTime;
    $.setTimeSort = setTimeSort;
})();
