/*
 * Copyright (C) 2016-2019 phantombot.tv
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * @author IllusionaryOne
 */

/*
 * greetingsPanel.js
 * Drives the Greetings Panel
 */
(function() {

    var refreshIcon = '<i class="fa fa-refresh" />',
        spinIcon = '<i style="color: var(--main-color)" class="fa fa-spinner fa-spin" />',
        settingIcon = [];
        settingIcon['false'] = '<i style="color: var(--main-color)" class="fa fa-circle-o" />';
        settingIcon['true'] = '<i style="color: var(--main-color)" class="fa fa-circle" />';

    var greetingToggle = false,
        followerToggle = false,
        subToggle = false,
        reSubToggle = false,
        subGiftToggle = false,
        massSubGiftToggle = false,
        donationToggle = false,
        donationGroup = false,
        gameWhispToggle = false,
        primeSubToggle = false,
        bitsToggle = false,
        bitsRewardMultToggle = false,
        tipeeestreamdonationToggle = false,
        tipeeestreamdonationGroup = false,
        streamelementsdonationToggle = false,
        streamelementsdonationGroup = false;

    /*
     * onMessage
     * This event is generated by the connection (WebSocket) object.
     */
    function onMessage(message) {
        var msgObject;

        try {
            msgObject = JSON.parse(message.data);
        } catch (ex) {
            return;
        }

        if (panelHasQuery(msgObject)) {
            var key = "",
                value = "";

            if (panelCheckQuery(msgObject, 'greetings_greeting')) {
                for (idx in msgObject['results']) {
                    key = msgObject['results'][idx]['key'];
                    value = msgObject['results'][idx]['value'];

                    if (panelMatch(key, 'autoGreetEnabled')) {
                        greetingToggle = value;
                        $('#globalGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'cooldown')) {
                        $('#greetingCooldownInput').val((value / 36e5));
                    }
                }
            }

            if (panelCheckQuery(msgObject, 'greetings_followReward')) {
                $('#followerRewardInput').val(msgObject['results']['followReward']);
            }

            if (panelCheckQuery(msgObject, 'greetings_followMessage')) {
                $('#followerGreetingInput').val(msgObject['results']['followMessage']);
            }

            if (panelCheckQuery(msgObject, 'greetings_followToggle')) {
                followToggle = msgObject['results']['followToggle'];
                $('#followerGreetings').html(settingIcon[msgObject['results']['followToggle']]);
            }

            if (panelCheckQuery(msgObject, 'greetings_followDelay')) {
                $('#followDelay').val( msgObject['results']['followDelay']);
            }

            if (panelCheckQuery(msgObject, 'greetings_donation')) {
                for (idx in msgObject['results']) {
                    key = msgObject['results'][idx]['key'];
                    value = msgObject['results'][idx]['value'];

                    if (panelMatch(key, 'announce')) {
                        donationToggle = value;
                        $('#donationGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'donationGroup')) {
                        donationGroup = value;
                        $('#donationGroup').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'donationGroupMin')) {
                        $('#donationGroupMin').val(value);
                    }
                    if (panelMatch(key, 'reward')) {
                        $('#donateRewardInput').val(value);
                    }
                    if (panelMatch(key, 'message')) {
                        $('#donateGreetingInput').val(value);
                    }
                }
            }

            if (panelCheckQuery(msgObject, 'greetings_tipeeestream')) {
                for (idx in msgObject['results']) {
                    key = msgObject['results'][idx]['key'];
                    value = msgObject['results'][idx]['value'];

                    if (panelMatch(key, 'toggle')) {
                        tipeeestreamdonationToggle = value;
                        $('#tipeeestreamGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'group')) {
                        tipeeestreamdonationGroup = value;
                        $('#tipeeestreamdonationGroup').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'groupMin')) {
                        $('#tipeeestreamdonationGroupMin').val(value);
                    }
                    if (panelMatch(key, 'reward')) {
                        $('#tipeeestreamdonateRewardInput').val(value);
                    }
                    if (panelMatch(key, 'message')) {
                        $('#tipeeestreamdonateGreetingInput').val(value);
                    }
                }
            }

            if (panelCheckQuery(msgObject, 'greetings_streamelements')) {
                for (idx in msgObject['results']) {
                    key = msgObject['results'][idx]['key'];
                    value = msgObject['results'][idx]['value'];

                    if (panelMatch(key, 'toggle')) {
                        streamelementsdonationToggle = value;
                        $('#streamelementsGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'group')) {
                        streamelementsdonationGroup = value;
                        $('#streamelementsdonationGroup').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'groupMin')) {
                        $('#streamelementsdonationGroupMin').val(value);
                    }
                    if (panelMatch(key, 'reward')) {
                        $('#streamelementsdonateRewardInput').val(value);
                    }
                    if (panelMatch(key, 'message')) {
                        $('#streamelementsdonateGreetingInput').val(value);
                    }
                }
            }

            if (panelCheckQuery(msgObject, 'greetings_subscribers')) {
                for (idx in msgObject['results']) {
                    key = msgObject['results'][idx]['key'];
                    value = msgObject['results'][idx]['value'];

                    if (panelMatch(key, 'subscribeMessage')) {
                        $('#subGreetingInput').val(value);
                    }
                    if (panelMatch(key, 'primeSubscribeMessage')) {
                        $('#primeSubGreetingInput').val(value);
                    }
                    if (panelMatch(key, 'reSubscribeReward')) {
                        $('#reSubRewardInput').val(value);
                    }
                    if (panelMatch(key, 'giftSubReward')) {
                        $('#giftSubRewardInput').val(value);
                    }
                    if (panelMatch(key, 'massGiftSubReward')) {
                        $('#massGiftSubRewardInput').val(value);
                    }
                    if (panelMatch(key, 'reSubscribeMessage')) {
                        $('#resubGreetingInput').val(value);
                    }
                    if (panelMatch(key, 'giftSubMessage')) {
                        $('#giftsubGreetingInput').val(value);
                    }
                    if (panelMatch(key, 'massGiftSubMessage')) {
                        $('#massGiftsubGreetingInput').val(value);
                    }
                    if (panelMatch(key, 'subscriberWelcomeToggle')) {
                        subToggle = value;
                        $('#subscriptionGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'primeSubscriberWelcomeToggle')) {
                        primeSubToggle = value;
                        $('#primeSubscriptionGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'reSubscriberWelcomeToggle')) {
                        reSubToggle = value;
                        $('#resubscriptionGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'giftSubWelcomeToggle')) {
                        subGiftToggle = value;
                        $('#subscriptiongiftGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'massGiftSubWelcomeToggle')) {
                        massSubGiftToggle = value;
                        $('#masssubscriptiongiftGreetings').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'subscribeReward')) {
                        $('#subRewardInput').val(value);
                    }
                    if (panelMatch(key, 'resubEmote')) {
                        $('#resubEmoteInput').val(value);
                    }
                    if (panelMatch(key, 'subPlan1000')) {
                        $('#subPlan1000Input').val(value);
                    }
                    if (panelMatch(key, 'subPlan2000')) {
                        $('#subPlan2000Input').val(value);
                    }
                    if (panelMatch(key, 'subPlan3000')) {
                        $('#subPlan3000Input').val(value);
                    }

                }
            }

            if (panelCheckQuery(msgObject, 'greetings_bits')) {
                for (idx in msgObject['results']) {
                    key = msgObject['results'][idx]['key'];
                    value = msgObject['results'][idx]['value'];

                    if (panelMatch(key, 'toggle')) {
                        bitsToggle = value;
                        $('#bitsToggle').html(settingIcon[value]);
                    }
                    if (panelMatch(key, 'message')) {
                        $('#bitsMessage').val(value);
                    }
                    if (panelMatch(key, 'minimum')) {
                        $('#bitsMinimum').val(value);
                    }
                }
            }
        }
    }

    /**
     * @function doQuery
     */
    function doQuery() {
        sendDBKeys('greetings_greeting', 'greeting');
        sendDBQuery('greetings_followReward', 'settings', 'followReward');
        sendDBQuery('greetings_followMessage', 'settings', 'followMessage');
        sendDBQuery('greetings_followToggle', 'settings', 'followToggle');
        sendDBQuery('greetings_followDelay', 'settings', 'followDelay');
        sendDBKeys('greetings_donation', 'donations');
        sendDBKeys('greetings_subscribers', 'subscribeHandler');
        sendDBKeys('greetings_bits', 'bitsSettings');
        sendDBKeys('greetings_tipeeestream', 'tipeeeStreamHandler');
        sendDBKeys('greetings_streamelements', 'streamElementsHandler');
    }

    /**
     * @function toggleGreetings
     * @param {String} table
     * @param {String} key
     */
    function toggleGreetings(table, key) {
        if (panelMatch(table, 'greeting')) {
            $('#globalGreetings').html(spinIcon);
            if (greetingToggle == "true") {
                sendDBUpdate('greetings_greeting', 'greeting', 'autoGreetEnabled', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'greeting', 'autoGreetEnabled', 'true');
            }
            setTimeout(function() { sendCommand('greetingspanelupdate'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'settings')) { // Confusing? Follow is in the settings table.
            $('#followerGreetings').html(spinIcon);
            if (followToggle == "true") {
                sendDBUpdate('greetings_greeting', 'settings', 'followToggle', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'settings', 'followToggle', 'true');
            }
            setTimeout(function() { sendCommand('followerpanelupdate'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'donations')) {
            $('#donationGreetings').html(spinIcon);
            if (donationToggle == "true") {
                sendDBUpdate('greetings_greeting', 'donations', 'announce', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'donations', 'announce', 'true');
            }
            setTimeout(function() { sendCommand('donationpanelupdate'); }, TIMEOUT_WAIT_TIME);
        }

        if (panelMatch(table, 'tipeeestream')) {
            $('#tipeeestreamGreetings').html(spinIcon);
            if (tipeeestreamdonationToggle == "true") {
                sendDBUpdate('greetings_greeting', 'tipeeeStreamHandler', 'toggle', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'tipeeeStreamHandler', 'toggle', 'true');
            }
            setTimeout(function() { sendCommand('tipeeestreamreload'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'streamelements')) {
            $('#streamelementsGreetings').html(spinIcon);
            if (streamelementsdonationToggle == "true") {
                sendDBUpdate('greetings_greeting', 'streamElementsHandler', 'toggle', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'streamElementsHandler', 'toggle', 'true');
            }
            setTimeout(function() { sendCommand('streamelementsreload'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'donationGroup')) {
            $('#donationGroup').html(spinIcon);
            if (donationGroup == "true") {
                sendDBUpdate('greetings_greeting', 'donations', 'donationGroup', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'donations', 'donationGroup', 'true');
            }
            setTimeout(function() { sendCommand('donationpanelupdate'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'tipeeestreamdonationGroup')) {
            $('#tipeeestreamdonationGroup').html(spinIcon);
            if (tipeeestreamdonationGroup == "true") {
                sendDBUpdate('greetings_greeting', 'tipeeeStreamHandler', 'group', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'tipeeeStreamHandler', 'group', 'true');
            }
            setTimeout(function() { sendCommand('tipeeestreamreload'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'streamelementsdonationGroup')) {
            $('#streamelementsdonationGroup').html(spinIcon);
            if (streamelementsdonationGroup == "true") {
                sendDBUpdate('greetings_greeting', 'streamElementsHandler', 'group', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'streamElementsHandler', 'group', 'true');
            }
            setTimeout(function() { sendCommand('streamelementsreload'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'subscribeHandler') && panelMatch(key, 'subscriberWelcomeToggle')) {
            $('#subscriptionGreetings').html(spinIcon);
            if (subToggle == "true") {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'subscriberWelcomeToggle', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'subscriberWelcomeToggle', 'true');
            }
            setTimeout(function() { sendCommand('subscriberpanelupdate'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'subscribeHandler') && panelMatch(key, 'primeSubscriberWelcomeToggle')) {
            $('#primeSubscriptionGreetings').html(spinIcon);
            if (primeSubToggle == "true") {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'primeSubscriberWelcomeToggle', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'primeSubscriberWelcomeToggle', 'true');
            }
            setTimeout(function() { sendCommand('subscriberpanelupdate'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'subscribeHandler') && panelMatch(key, 'reSubscriberWelcomeToggle')) {
            $('#resubscriptionGreetings').html(spinIcon);
            if (reSubToggle == "true") {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'reSubscriberWelcomeToggle', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'reSubscriberWelcomeToggle', 'true');
            }
            setTimeout(function() { sendCommand('subscriberpanelupdate'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'subscribeHandler') && panelMatch(key, 'giftSubWelcomeToggle')) {
            $('#subscriptiongiftGreetings').html(spinIcon);
            if (subGiftToggle == "true") {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'giftSubWelcomeToggle', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'giftSubWelcomeToggle', 'true');
            }
            setTimeout(function() { sendCommand('subscriberpanelupdate'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'subscribeHandler') && panelMatch(key, 'massGiftSubWelcomeToggle')) {
            $('#masssubscriptiongiftGreetings').html(spinIcon);
            if (massSubGiftToggle == "true") {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'massGiftSubWelcomeToggle', 'false');
            } else {
                sendDBUpdate('greetings_greeting', 'subscribeHandler', 'massGiftSubWelcomeToggle', 'true');
            }
            setTimeout(function() { sendCommand('subscriberpanelupdate'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'bitsSettings') && panelMatch(key, 'toggle')) {
            $('#bitsToggle').html(spinIcon);
            if (bitsToggle == "true") {
                sendDBUpdate('greetings_bits', 'bitsSettings', 'toggle', 'false');
            } else {
                sendDBUpdate('greetings_bits', 'bitsSettings', 'toggle', 'true');
            }
            setTimeout(function() { sendCommand('reloadbits'); }, TIMEOUT_WAIT_TIME);
        }
        if (panelMatch(table, 'bitsSettings') && panelMatch(key, 'rewardMultToggle')) {
            $('#bitsRewardMultToggle').html(spinIcon);
            if (bitsRewardMultToggle == "true") {
                sendDBUpdate('greetings_bits', 'bitsSettings', 'rewardMultToggle', 'false');
            } else {
                sendDBUpdate('greetings_bits', 'bitsSettings', 'rewardMultToggle', 'true');
            }
            setTimeout(function() { sendCommand('reloadbits'); }, TIMEOUT_WAIT_TIME);
        }
        setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME);
    }

    /**
     * @function updateGreetingData
     * @param {String} inputId
     * @param {String} table
     * @param {String} key
     */
    function updateGreetingData(inputId, table, key) {
        var value = $('#' + inputId).val();

        if (inputId == "greetingCooldownInput") {
            if (value.length > 0) {
                value = String(value * 36e5);
                sendDBUpdate('greetings_update', 'greeting', 'cooldown', value);
                setTimeout(function() { doQuery(); sendCommand('greetingspanelupdate'); }, TIMEOUT_WAIT_TIME);
                return;
            }
        }

        if (key == 'followDelay') {
            if (parseInt(value) < 5) {
                document.getElementById(inputId).type = 'text';
                $('#' + inputId).val('Follow delay cannot be less than 5 seconds!');
                setTimeout(function() { doQuery(); document.getElementById(inputId).type = 'number'; }, TIMEOUT_WAIT_TIME * 4);
                return;
            }
        }

        if (value.length > 0) {
            sendDBUpdate('greetings_update', table, key, value);

            if (panelMatch(table, 'greeting')) {
                sendCommand('greetingspanelupdate');
            }
            if (panelMatch(table, 'settings')) { // Confusing? Follow is in the settings table.
                sendCommand('followerpanelupdate');
            }
            if (panelMatch(table, 'donations')) {
                sendCommand('donationpanelupdate');
            }
            if (panelMatch(table, 'subscribeHandler')) {
                sendCommand('subscriberpanelupdate');
            }
            if (panelMatch(table, 'bitsSettings')) {
                sendCommand('reloadbits');
            }
            if (panelMatch(table, 'tipeeeStreamHandler')) {
                sendCommand('tipeeestreamreload');
            }
            if (panelMatch(table, 'streamElementsHandler')) {
                sendCommand('streamelementsreload');
            }
            setTimeout(function() { doQuery(); }, TIMEOUT_WAIT_TIME * 2);
        }
    }


    // Import the HTML file for this panel.
    $('#greetingsPanel').load('/panel/greetings.html');

    // Load the DB items for this panel, wait to ensure that we are connected.
    var interval = setInterval(function() {
        if (isConnected && TABS_INITIALIZED) {
            var active = $("#tabs").tabs("option", "active");
            if (active == 7) {
                doQuery();
                clearInterval(interval);
            }
        }
    }, INITIAL_WAIT_TIME);

    // Query the DB every 30 seconds for updates.
    setInterval(function() {
        var active = $('#tabs').tabs('option', 'active');
        if (active == 7 && isConnected && !isInputFocus()) {
            newPanelAlert('Refreshing Greeting Data', 'success', 1000);
            doQuery();
        }
    }, 3e4);

    // Export functions - Needed when calling from HTML.
    $.greetingsOnMessage = onMessage;
    $.greetingsDoQuery = doQuery;
    $.toggleGreetings = toggleGreetings;
    $.updateGreetingData = updateGreetingData;
    $.updateGWTierData = updateGWTierData;
})();
