// Configuration for Control Panel
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelSettings = {
    panelPort   : 8880,
    channelName : "scaniatv",
    auth        : "JzN82n8glKdEkUpacEeCdqapaJgaq0",
    http        : "http://"
,     displayName : "ScaniaTV"
, };

function getPanelPort() { return panelSettings.panelPort; }
function getChannelName() { return panelSettings.channelName; }
function getAuth() { return panelSettings.auth; }
function getProtocol() { return panelSettings.http; }
function getDisplayName() { return panelSettings.displayName; }
