$.lang.register('randomcommand.1', '(sender) was thrown into a large pit of PJSalt');
$.lang.register('randomcommand.2', 'Oh my, (sender) you make me just want to *SLURP SLURP SLURP*');
$.lang.register('randomcommand.3', '(sender) was thrown into a pit of tentacle pleasure.');
$.lang.register('randomcommand.4', '(sender) was thrown into a pit of genetically modified super lions.');
$.lang.register('randomcommand.5', '(sender) was thrown into a pit of explosive prinnies.');
$.lang.register('randomcommand.6', 'I want you (sender).');
$.lang.register('randomcommand.7', '/me threw (sender) into a pit of PJSalt');
$.lang.register('randomcommand.8', 'Dango, dango, dango, dango, big (sender) family~\u266B');
$.lang.register('randomcommand.9', 'What are we gonna\' do on the bed (sender)?');
$.lang.register('randomcommand.10', 'Your mother was a hamster and your father smelt of elderberries!');
$.lang.register('randomcommand.11', 'When life gives you lemons (sender), make orange juice and leave the world wondering how the hell you did it.');
$.lang.register('randomcommand.12', '(sender) was violated by a tentacle monster on stream.');
$.lang.register('randomcommand.13', '/me licked (sender). . .');
$.lang.register('randomcommand.14', 'This is the first time (sender) has noticed the scent of a woman..');
$.lang.register('randomcommand.15', '/me licking intensifies!');
$.lang.register('randomcommand.16', 'I hope (sender)-senpai notices me..');
$.lang.register('randomcommand.17', '(sender) is so awesome because (sender) can trip over flat surfaces, fall up the stairs!!');
$.lang.register('randomcommand.18', '(sender) looks good enough to dress like the grim reaper and go to a retirement home and tap on the windows!');
$.lang.register('randomcommand.19', 'Ok everyone shhhhh. The rice crispies are telling me what to do next.');
$.lang.register('randomcommand.20', '(sender) made eye contact with (random) while eating a banana!');
$.lang.register('randomcommand.21', '(random) mysteriously died.');
$.lang.register('randomcommand.22', '(random) stopped existing.');
$.lang.register('randomcommand.23', 'All 7 of the Dragon Balls have been gathered! Now to wish (sender) to become a sloth!');
$.lang.register('randomcommand.24', 'The ocean is so salty because everyone pees in it.');
$.lang.register('randomcommand.25', 'Real men know when to run like a little bitch');
$.lang.register('randomcommand.26', 'If I get reincarnated…. I wanna be a clam.');
$.lang.register('randomcommand.27', 'Why don’t we drink to me and my reflection in your lovely eyes?');
$.lang.register('randomcommand.28', 'I can show you what color your brain is.');
$.lang.register('randomcommand.29', 'And while you’re waiting for us to kill you, we highly recommend p*ssing yourself, Followed by a course of praying to your impudent god. And cowarding in the corner and begging, always good. But if you act now, theres still time for an old-fashioned Suicide!! Thank you London! We love you! goodnight!!');
$.lang.register('randomcommand.30', 'If you die, don’t come crying to me about it.');
$.lang.register('randomcommand.31', 'From this point on, all your opinions will be rejected!');
$.lang.register('randomcommand.32', 'Kakarot! Is That A Vegetable?! I Hate Vegetables.');
$.lang.register('randomcommand.33', 'I see. (sender) is the type of person who is thinking positively to the extent of being stupid.');
$.lang.register('randomcommand.34', 'I know as much of games as hugs and puppies, and care for them even less.');
$.lang.register('randomcommand.35', 'I’m not just a pervert…I’M A SUPER PERVERT');
$.lang.register('randomcommand.36', 'When you meet with scary people, you must always protect your wallet and anus!');
$.lang.register('randomcommand.37', 'Women’s minds and Autumn Winds change often.');
$.lang.register('randomcommand.38', 'I’m literally haemorrhaging generosity.');
$.lang.register('randomcommand.39', 'They were traps? I thought they were attractions.');
$.lang.register('randomcommand.40', 'Okay, here’s the plan: We go in, start hitting people, and see where it takes us.');
$.lang.register('randomcommand.41', 'The key in turning people on is a girl with a lolita face and big breasts.');
$.lang.register('randomcommand.42', 'When a woman says something cute, a man just can’t trust it.');
$.lang.register('randomcommand.43', 'A life without gambling is like sushi without wasabi.');
$.lang.register('randomcommand.44', 'Stress makes you bald, but it’s stressful to avoid stress, so you end up stressed out anyway, so in the end there’s nothing you can do.');
$.lang.register('randomcommand.45', 'Do evil, get caught, then claim demons were brainwashing you. A common way that human politicians evade responsibility.');
$.lang.register('randomcommand.46', 'I have one last request. Please slap me in the face with that wad of cash.');
$.lang.register('randomcommand.47', 'Why do people have to work? I just want to eat and sleep. I should have been born as a panda at the zoo.');
$.lang.register('randomcommand.48', 'Right, I have something I have to apologize to (random) for. Sometimes, when we were playing, you’d suddenly start crying, and then you’d run home. You probably thought you’d fooled us, but everyone knew… that you had pooped your pants! Sorry.');
$.lang.register('randomcommand.49', 'What I want to do most? Let’s see… Just once, I really want to let loose and pee in my pants.');
$.lang.register('randomcommand.50', 'Dude! Christmas rocks! We know how to do it right, here! First, we X out the ‘Christ’ part to make it extreme! Then we shop and eat stuff ’til we’re sick! Wanna shovel down some X-Mas cake to get in the spirit?');
$.lang.register('randomcommand.51', 'My name is Duck. Yes, like the bird. Take it up with my parents. They never loved me!');
$.lang.register('randomcommand.52', '(sender), during your last physical it was discovered you have Athletes Foot, and we now believe it is affecting your brain.');
$.lang.register('randomcommand.53', 'When you have a swimsuit tan. You could jump in the pool naked and no one would know you weren’t wearing anything.');
$.lang.register('randomcommand.54', 'I came to laugh at you - Chars Aznabal (Gundam)');
$.lang.register('randomcommand.55', 'You\'re thinking in Japanese! If you must think, do it in German!');
$.lang.register('randomcommand.56', '*bursts into tears* I can\'t talk about it! It\'s so horrible! They were-- they were-- the milk! Oh God, the milk!');
$.lang.register('randomcommand.57', 'Panties, Panties, Panties');
$.lang.register('randomcommand.58', 'Now I understand the relieved, I feel very situation...');
$.lang.register('randomcommand.59', 'Come on, scribbles on the bathroom wall, please show me the path that I must follow!');
$.lang.register('randomcommand.60', 'Please don\'t worry, Mister, I only came here to obliterate you- not rob you.');
$.lang.register('randomcommand.61', '... if you let the fly live, the spider is going to die. You can\'t save both without one suffering..');
$.lang.register('randomcommand.62', 'Bansai, bathtoy, wise guy, waterboy, lights shine bright in the o-town tonight');
$.lang.register('randomcommand.63', 'Faye faye smoke smoke, faye faye puff puff! Yay!');
$.lang.register('randomcommand.64', 'Total slaughter, total slaughter. I won\'t leave a single man alive. La dee da dee dide, genocide. La dee da dee dud, an ocean of blood. Let\'s begin the killing time.');
$.lang.register('randomcommand.65', 'Someone once told me...that watching the birds made them want to go on a journey...');
$.lang.register('randomcommand.66', 'I wouldn\'t mind if you want to kill me, but I might struggle a bit');
$.lang.register('randomcommand.67', 'I think I know, I don\'t think I know, I don\'t think I think I know, I don\'t think I think.');
$.lang.register('randomcommand.68', 'I love to stand in line at ATM machines, and when people put in their PIN, I yell GOT IT then run away');
$.lang.register('randomcommand.69', 'Like a weird neighbour, stalkers are there!');
$.lang.register('randomcommand.70', 'OK think of a number. Add 12 to the number. Subtract 2. Divide that number by 5. Add 20. Did you get 12? Neither did I. I just wanted to see if you would do it!');
$.lang.register('randomcommand.71', 'If somebody throws skittles at me and yells "TASTE THE RAINBOW", I\'m gonna throw a 2 liter bottle of Dr.Pepper and yell "TRUST ME I\'M THE DOCTOR."');
$.lang.register('randomcommand.72', 'A few days ago I very sternly told the voices in my head to stop talking to Me. Now they are sending me txt mgs say that they r sorry and want to get back2gethr.');
$.lang.register('randomcommand.73', 'Things to do at Walmart: hide behind teddy bears and make evil laughing noises when little kids come by.');
$.lang.register('randomcommand.74', 'Ever feel like beating someone with a baseball bat to the point of almost unconsciousness, then setting them on fire? No? Just me?');
$.lang.register('randomcommand.75', 'I\'m not crazy.. don\'t you judge me! Your just jealous cause I get texts from the flying gummy bears and you don\'t!');
$.lang.register('randomcommand.76', 'I saw a flying cow yesterday. It was purple and I named him Phillip...I wish the dancing unicorn had seen him but she was too busy laughing at Steve the snake');
$.lang.register('randomcommand.77', 'I was sitting there when I got attacked by the purple hedgehogs, neon dragons, and glow-in-the-dark leprechauns that kid-napped the unicorn and strawberry king');
$.lang.register('randomcommand.78', 'I have decided to stop pretending and just be that ninja with the magical penguins and dinosaurs and unicorns that everyone KNOWS I am.');
$.lang.register('randomcommand.79', 'Have you ever tried walking into Walmart and yelling red robin! and seeing how many people say YUM red robin, red robin, come on just say yum!');
$.lang.register('randomcommand.80', 'Things to do at Walmart #365: bring or take a tent, set it up in a camping supplies corner, and camp out for the weekend until they kick you out!');
$.lang.register('randomcommand.81', 'After watching CSI, Cold case, Law & Order, and all those other educational shows, I\'m 99% sure I can make sure nobody notices you missing. Just saying...');
$.lang.register('randomcommand.82', 'I like to call it doing the world a favor. Homicide is just the technical term.');
$.lang.register('randomcommand.83', 'I think there\'s something wrong with my guardian angel. Her wings are black and she\'s sitting with the devil and laughing hysterically at everything and everyone.');
$.lang.register('randomcommand.84', 'I got a special care pkg. in the mail. It had duct tape, a meat tenderizer, a hole punch and a note saying "Don\'t get caught"! (sigh) I love my friends!');
$.lang.register('randomcommand.85', 'Backwards this read you making am I why exactly is that, never? you to nice been ever I have when since (now read it backwards).');
$.lang.register('randomcommand.86', 'What happens in an exam : Tik tok, Mind block, Pen stop, Eye pop, Full shock, Jaw drop, Time up, No Luck');
$.lang.register('randomcommand.87', 'I dare you to walk up to any officer and say: I didnt do it I didnt kill her, the assassination wasnt part of the plan.\' Then run fast! I bet they\'ll chase you.');
$.lang.register('randomcommand.88', 'I\'m bored & in need of some adventure. I say we get drunk, get stupid, get a stick, go poke something with teeth and see if we can outrun it.');
$.lang.register('randomcommand.89', 'Why do people always think my friends and I are high? WE\'RE NOT ON DRUGS! We\'re just crazy, and loud, and random, and scooby doo (but that\'s a different story).');
$.lang.register('randomcommand.90', 'Smile and people will wonder what your up to. But grin like crazy and they will want to know what the hell you just did.');
$.lang.register('randomcommand.91', 'Isn\'t it funny how everyone thinks they are the normal one in their family?');
$.lang.register('randomcommand.92', 'For Sale! One used alarm clock. damn thing rings when I am trying to sleep.');
$.lang.register('randomcommand.93', 'I\'m on my way to Walmart to take the "try me" stickers off the noise making toys and stick them on condom boxes.');
$.lang.register('randomcommand.94', 'A woman gets on a bus with her baby. The bus driver says: \'\'Ugh, that\'s the ugliest baby I\'ve ever seen!\'\' The woman walks to the rear of the bus and sits down, fuming. She says to a man next to her: \'\'The driver just insulted me!\'\' The man says: \'\'You go up there and tell him off. Go on, I\'ll hold your monkey for you.\'\'');
$.lang.register('randomcommand.95', '\'\'I went to the zoo the other day, there was only one dog in it, it was a shitzu.\'\'');
$.lang.register('randomcommand.96', '\'\'Dyslexic man walks into a bra\'\'');
$.lang.register('randomcommand.97', 'A young blonde woman is distraught because she fears her husband is having an affair, so she goes to a gun shop and buys a handgun. The next day she comes home to find her husband in bed with a beautiful redhead. She grabs the gun and holds it to her own head. The husband jumps out of bed, begging and pleading with her not to shoot herself. Hysterically the blonde responds to the husband, \'\'Shut up...you\'re next!\'\'');
$.lang.register('randomcommand.98', 'A classic Tommy Cooper gag \'\'I said to the Gym instructor "Can you teach me to do the splits?" He said, "How flexible are you?" I said, "I can\'t make Tuesdays", was fifth.');
$.lang.register('randomcommand.99', 'Police arrested two kids yesterday, one was drinking battery acid, the other was eating fireworks. They charged one - and let the other one off.');
$.lang.register('randomcommand.100', 'Two aerials meet on a roof - fall in love - get married.  The ceremony was rubbish - but the reception was brilliant.');
$.lang.register('randomcommand.101', 'Another one was:  Doc, I can\'t stop singing the \'Green Green Grass of Home\'. He said: \'That sounds like Tom Jones syndrome\'. \'Is it common?\'I asked.  \'It\'s not unusual\' he replied.');
$.lang.register('randomcommand.102', 'I\'m on a whiskey diet. I\'ve lost three days already.');
$.lang.register('randomcommand.103', 'A man walks into a bar with a roll of tarmac under his arm and says: \'\'Pint please, and one for the road.\'\'');
$.lang.register('randomcommand.104', 'I went to the doctors the other day and I said, \'Have you got anything for wind?\' So he gave me a kite.');
$.lang.register('randomcommand.105', 'My mother-in-law fell down a wishing well, I was amazed, I never knew they worked.');
$.lang.register('randomcommand.106', 'I saw this bloke chatting up a cheetah; I thought, He\'s trying to pull a fast one.');
$.lang.register('randomcommand.107', 'A woman has twins, and gives them up for adoption. One of them goes to a family in Egypt and is named "Amal". The other goes to a family in Spain, they name him "Juan". Years later Juan sends a picture of himself to his mum. Upon receiving the picture, she tells her husband that she wished she also had a picture of Amal. Her husband responds, But they are twins. If you\'ve seen Juan, you\'ve seen Amal.');
$.lang.register('randomcommand.108', 'There\'s two fish in a tank, and one says \'\'How do you drive this thing?\'\'');
$.lang.register('randomcommand.109', 'I went to buy some camouflage trousers the other day but I couldn\'t find any.');
$.lang.register('randomcommand.110', 'When Susan\'s boyfriend proposed marriage to her she said: \'\'I love the simple things in life, but I don\'t want one of them for my husband\'\'.');
$.lang.register('randomcommand.111', '\'\'My therapist says I have a preoccupation with vengeance. We\'ll see about that.\'\'');
$.lang.register('randomcommand.112', 'I rang up British Telecom, I said, \'\'I want to report a nuisance caller\'\', he said \'\'Not you again\'\'.');
$.lang.register('randomcommand.113', 'I met a Dutch girl with inflatable shoes last week, phoned her up to arrange a date but unfortunately she\'d popped her clogs.');
$.lang.register('randomcommand.114', 'A jump-lead walks into a bar. The barman says \'\'I\'ll serve you, but don\'t start anything\'\'');
$.lang.register('randomcommand.115', 'Slept like a log last night........ Woke up in the fireplace.');
$.lang.register('randomcommand.116', 'A priest, a rabbi and a vicar walk into a bar. The barman says, \'\'Is this some kind of joke?\'\'');
$.lang.register('randomcommand.117', 'A sandwich walks into a bar. The barman says \'\'Sorry we don\'t serve food in here\'\'');
$.lang.register('randomcommand.118', 'The other day I sent my girlfriend a huge pile of snow. I rang her up, I said \'\'Did you get my drift?\'\'.');
$.lang.register('randomcommand.119', 'I cleaned the attic with the wife the other day. Now I can\'t get the cobwebs out of her hair.');
$.lang.register('randomcommand.120', 'Went to the paper shop - it had blown away.');
$.lang.register('randomcommand.121', 'A group of chess enthusiasts checked into a hotel and were standing in the lobby discussing their recent tournament victories. After about an hour, the manager came out of the office and asked them to disperse. \'\'But why?\'\' they asked, as they moved off. \'\'because,\'\' he said \'\'I can\'t stand chess nuts boasting in an open foyer.\'\'');
$.lang.register('randomcommand.122', 'I was in Tesco\'s and I saw this man and woman wrapped in a barcode. I said, \'\'Are you two an item?\'\'');
$.lang.register('randomcommand.123', 'I\'m in great mood tonight because the other day I entered a competition and I won a years supply of Marmite......... one jar.');
$.lang.register('randomcommand.124', 'So I went to the Chinese restaurant and this duck came up to me with a red rose and says \'\'Your eyes sparkle like diamonds\'\'. I said, \'\'Waiter, I asked for a-ROMATIC duck\'\'.');
$.lang.register('randomcommand.125', 'I was having dinner with Garry Kasporov (world chess champion) and there was a check tablecloth. It took him two hours to pass me the salt.');
$.lang.register('randomcommand.126', 'There was a man who entered a local paper\'s pun contest.. He sent in ten different puns, in the hope that at least one of the puns would win. Unfortunately, no pun in ten did.');
$.lang.register('randomcommand.127', 'I went down the local supermarket, I said, \'\'I want to make a complaint, this vinegar\'s got lumps in it\'\', he said, "Those are pickled onions".');
$.lang.register('randomcommand.128', 'I backed a horse last week at ten to one.  It came in at quarter past four.');
$.lang.register('randomcommand.129', 'I swear, the other day I bought a packet of peanuts, and on the packet it said \'\'may contain nuts.\'\' Well, YES! That\'s what I bought the buggers for! You\'d be annoyed if you opened it and a socket set fell out!\'\'');
$.lang.register('randomcommand.130', 'A lorry-load of tortoises crashed into a trainload of terrapins, What a turtle disaster');
$.lang.register('randomcommand.131', 'My phone will ring at 2 in the morning, and my wife\'ll look at me and go, \'\'Who\'s that calling at this time?\' \'\'I don\'t know! If I knew that we wouldn\'t need the bloody phone!\'\'');
$.lang.register('randomcommand.132', 'I said to this train driver \'\'I want to go to Paris". He said "Eurostar?" I said, "I\'ve been on telly but I\'m no Dean Martin".');
$.lang.register('randomcommand.133', 'Two Eskimos sitting in a kayak were chilly. But when they lit a fire in the craft, it sank, proving once and for all that you can\'t have your kayak and heat it.');
$.lang.register('randomcommand.134', 'I\'ve got a friend who\'s fallen in love with two school bags, he\'s bisatchel.');
$.lang.register('randomcommand.135', 'You see my next-door neighbour worships exhaust pipes, he\'s a catholic converter.');
$.lang.register('randomcommand.136', 'A three-legged dog walks into a saloon in the Old West. He slides up to the bar and announces: \'\'I\'m looking for the man who shot my paw.\'\'');
$.lang.register('randomcommand.137', 'I tried water polo but my horse drowned.');
$.lang.register('randomcommand.138', 'I\'ll tell you what I love doing more than anything: trying to pack myself in a small suitcase. I can hardly contain myself.');
$.lang.register('randomcommand.139', 'So I met this gangster who pulls up the back of people\'s pants, it was Wedgie Kray.');
$.lang.register('randomcommand.140', 'Went to the corner shop - bought 4 corners.');
$.lang.register('randomcommand.141', 'A seal walks into a club...');
$.lang.register('randomcommand.142', 'I went to the Doctors the other day, and he said, \'Go to Bournemouth, it\'s great for flu\'. So I went  -  and I got it.');
$.lang.register('randomcommand.143', 'Fun at Walmart #1. Take shopping carts for the express purpose of filling them and stranding them at strategic locations.');
$.lang.register('randomcommand.144', 'Fun at Walmart #2. Ride those little electronic cars at the front of the store.');
$.lang.register('randomcommand.145', 'Fun at Walmart #3. Set all the alarm clocks to go off at ten-minute intervals throughout the day');
$.lang.register('randomcommand.146', 'Fun at Walmart #4. Start playing Calvinball; see how many people you can get to join');
$.lang.register('randomcommand.147', 'Fun at Walmart #5. Contaminate the entire auto department by sampling all the spray air fresheners.');
$.lang.register('randomcommand.148', 'Fun at Walmart #6. Challenge other customers to duels with tubes of gift-wrap.');
$.lang.register('randomcommand.149', 'Fun at Walmart #7. Leave cryptic messages on the typewriters.');
$.lang.register('randomcommand.150', 'Fun at Walmart #8. Re-dress the mannequins as you see fit.');
$.lang.register('randomcommand.151', 'Fun at Walmart #9. When there are people behind you, walk really slowly, especially in thin aisles.');
$.lang.register('randomcommand.152', 'Fun at Walmart #10. Walk up to an employee and tell him in an official tone, "I think we\'ve got a code 3 in housewares," and see what happens.');
$.lang.register('randomcommand.153', 'Fun at Walmart #11. Turn all the radios to polka stations; then turn them off and turn the volume up to full blast.');
$.lang.register('randomcommand.154', 'Fun at Walmart #12. Play with the automatic doors.');
$.lang.register('randomcommand.155', 'Fun at Walmart #13. Walk up to complete strangers and say, "Hi. I haven\'t seen you in so long." etc. See if they play along.');
$.lang.register('randomcommand.156', 'Fun at Walmart #14. While walking through the clothing department, ask yourself loud enough for all to hear, "Who buys this crap anyway?!"');
$.lang.register('randomcommand.157', 'Fun at Walmart #15. Repeat #14 in the jewelry department.');
$.lang.register('randomcommand.158', 'Fun at Walmart #16. Ride a display bicycle through the store; claim you are taking it for a test drive.');
$.lang.register('randomcommand.159', 'Fun at Walmart #17. Follow people through the aisles, staying about 5 feet behind them. Do this until they leave the store.');
$.lang.register('randomcommand.160', 'Fun at Walmart #18. Play soccer with a group of friends, using the entire store as your playing field.');
$.lang.register('randomcommand.161', 'Fun at Walmart #19. As the cashier runs your purchase over the scanner, look mesmerized and say, "Wow, magic!"');
$.lang.register('randomcommand.162', 'Fun at Walmart #20. Put M&M\'s on layaway.');
$.lang.register('randomcommand.163', 'Fun at Walmart #21. Move "Caution : Wet Floor" signs to carpeted areas.');
$.lang.register('randomcommand.164', 'Fun at Walmart #22. Set up a tent in the camping department; tell others you will only invite them in if they bring pillows from Bed and Bath.');
$.lang.register('randomcommand.165', 'Fun at Walmart #23. Test the fishing rods and see what you can catch from other aisles.');
$.lang.register('randomcommand.166', 'Fun at Walmart #24. Ask other customers if they have any Grey Poupon.');
$.lang.register('randomcommand.167', 'Fun at Walmart #25. Drape a blanket around your shoulders and run around saying, "I\'m Batman. Come Robin, to the Batcave."');
$.lang.register('randomcommand.168', 'Fun at Walmart #26. TP as much of the store as possible.');
$.lang.register('randomcommand.169', 'Fun at Walmart #27. Randomly throw things over into neighboring aisles.');
$.lang.register('randomcommand.170', 'Fun at Walmart #28. Play with the calculators so that they all spell "hello" upside down.');
$.lang.register('randomcommand.171', 'Fun at Walmart #29. When someone asks you if you need help, begin to cry and say, "Why won\'t you people just leave me alone?"');
$.lang.register('randomcommand.172', 'Fun at Walmart #30. When 2 or 3 people are walking ahead of you, run between them yelling "Red Rover."');
$.lang.register('randomcommand.173', 'Fun at Walmart #31. Make up nonsense products and ask employees if there are any in stock. (i.e.: Shnerples)');
$.lang.register('randomcommand.174', 'Fun at Walmart #32. Take up an entire aisle in toys by setting up a full-scale battle with G.I. Joe vs. X-men.');
$.lang.register('randomcommand.175', 'Fun at Walmart #33. Take bets on the battle from above.');
$.lang.register('randomcommand.176', 'Fun at Walmart #34. Test the brushes and combs in cosmetics.');
$.lang.register('randomcommand.177', 'Fun at Walmart #35. While handling guns in the hunting department, suddenly ask the clerk where the anti-depressants are. Act as spastic as possible.');
$.lang.register('randomcommand.178', 'Fun at Walmart #36. Hold indoor shopping cart races.');
$.lang.register('randomcommand.179', 'Fun at Walmart #37. Dart around suspiciously while humming the theme from Mission Impossible.');
$.lang.register('randomcommand.180', 'Fun at Walmart #38. Attempt to fit into very large gym bags.');
$.lang.register('randomcommand.181', 'Fun at Walmart #39. Attempt to fit others into very large gym bags.');
$.lang.register('randomcommand.182', 'Fun at Walmart #40. Say things like, "Would you be so kind as to direct me to your Twinkies."');
$.lang.register('randomcommand.183', 'Fun at Walmart #41. Set up a "Valet Parking" sign in front of the store.');
$.lang.register('randomcommand.184', 'Fun at Walmart #42. Two words: Marco Polo');
$.lang.register('randomcommand.185', 'Fun at Walmart #43. Leave Cheerios in lawn and garden, pillows in the pet section, etc.');
$.lang.register('randomcommand.186', 'Fun at Walmart #44. "Re-alphabetize" the CD\'s.');
$.lang.register('randomcommand.187', 'Fun at Walmart #45. In the auto department, practice your Madonna look with various funnels.');
$.lang.register('randomcommand.188', 'Fun at Walmart #46. When someone steps away from his or her cart to look at something, quickly make off with it without saying a word.');
$.lang.register('randomcommand.189', 'Fun at Walmart #47. Relax in the patio furniture until you get kicked out.');
$.lang.register('randomcommand.190', 'Fun at Walmart #48. When an announcement comes over the loudspeaker, drop to your knees and scream, "No, no, its those voices again."');
$.lang.register('randomcommand.191', 'Fun at Walmart #49. Pay off layaways 50 cents at a time.');
$.lang.register('randomcommand.192', 'Fun at Walmart #50. Drag a lounge chair over to the magazines and relax. Go to the food court, buy a drink, and explain that you don\'t get out much and ask if they can put a little umbrella in it.');
$.lang.register('randomcommand.193', 'Fun at a Drive thru #1. Drive through the drive thru in reverse and let your passenger order.');
$.lang.register('randomcommand.194', 'Fun at a Drive thru #2. Ask prices of everything on the menu then order something that you did not ask the price for.');
$.lang.register('randomcommand.195', 'Fun at a Drive thru #3. Pretend like your window is broken. Tell the employee this. Order with your door open, pay with your door open. Roll down window and take food through the window.');
$.lang.register('randomcommand.196', 'Fun at a Drive thru #4. Go to McDonalds and demand a big breakfast at 11:30 at night. Put up a fight.');
$.lang.register('randomcommand.197', 'Fun at a Drive thru #5. Pay for a large order in pennies and nickels unwrapped.');
$.lang.register('randomcommand.198', 'Fun at a Drive thru #6. Order in another language. Be careful what neighborhood you are in.');
$.lang.register('randomcommand.199', 'Fun at a Drive thru #7. When asked if they can take your order, tell them you are just window shopping and drive on.');
$.lang.register('randomcommand.200', 'Fun at a Drive thru #8. Laugh sadistically when asked if you would like ketchup.');
$.lang.register('randomcommand.201', 'Fun at a Drive thru #9. Ask how they fit into that little box.');
$.lang.register('randomcommand.202', 'Fun at a Drive thru #10. If they make you wait, make them wait when they come back on.');
$.lang.register('randomcommand.203', 'Fun at a Drive thru #11. Demand to speak to the manager. When he comes on, complain that you did not like the way the employee said "May I take your order?"');
$.lang.register('randomcommand.204', 'Fun at a Drive thru #12. When asked if they can take your order say "No, why can I take yours?"');
$.lang.register('randomcommand.205', 'Fun at a Drive thru #13. If they ask you to wait, order anyway and keep doing it till they yell at you.');
$.lang.register('randomcommand.206', 'Fun at a Drive thru #14. Pretend like your car broke down. Ask for assistance in moving it. When they come out, drive away.');
$.lang.register('randomcommand.207', 'Fun at a Drive thru #15. Tell them you have to use the bathroom.');
$.lang.register('randomcommand.208', 'Fun at a Drive thru #16. Order a cup of water and two napkins. That\'s it.');
$.lang.register('randomcommand.209', 'Fun at a Drive thru #17. Don\'t order when they come on. Just sit there. If a line forms behind you, get out of the car and cause a scene.');
$.lang.register('randomcommand.210', 'Fun at a Drive thru #18. When they hand you your food, hand them a bag back with all the trash from your car in it.');
$.lang.register('randomcommand.211', 'Fun at a Drive thru #19. Just stare at them when you pay and get your food. Don\'t break your stare.');
$.lang.register('randomcommand.212', 'Fun at a Drive thru #20. Honk your horn the whole way through the line.');
$.lang.register('randomcommand.213', 'If a pig loses its voice, is it disgruntled?');
$.lang.register('randomcommand.214', 'Why do women wear evening gowns to nightclubs? Shouldn\'t they be wearing night gowns?');
$.lang.register('randomcommand.215', 'If love is blind, why is lingerie so popular?');
$.lang.register('randomcommand.216', 'When someone asks you, "A penny for your thoughts," and you put your two cents in, what happens to the other penny?');
$.lang.register('randomcommand.217', 'Why is the man who invests all your money called a broker?');
$.lang.register('randomcommand.218', 'Why do croutons come in airtight packages? It\'s just stale bread to begin with.');
$.lang.register('randomcommand.219', 'When cheese gets it\'s picture taken, what does it say?');
$.lang.register('randomcommand.220', 'Why is a person who plays the piano called a pianist, but a person who drives a race car not called a racist?');
$.lang.register('randomcommand.221', 'Why are a wise man and a wise guy opposites?');
$.lang.register('randomcommand.222', 'Why do overlook and oversee mean opposite things?');
$.lang.register('randomcommand.223', 'If horrific means to make horrible, does terrific mean to make terrible?');
$.lang.register('randomcommand.224', '"I am." is reportedly the shortest sentence in the English language. Could it be that "I Do." is the longest sentence?');
$.lang.register('randomcommand.225', 'If lawyers are disbarred and clergymen defrocked, doesn\'t it follow that electricians can be delighted, musicians denoted, cowboys deranged, models deposed, tree surgeons debarked and drycleaners depressed?');
$.lang.register('randomcommand.226', 'Do Roman paramedics refer to IV\'s as "4\'s"?');
$.lang.register('randomcommand.227', 'Why is it that if someone tells you that there are 1 billion stars in the universe you will believe them, but if they tell you a wall has wet paint you will have to touch it to be sure?');
$.lang.register('randomcommand.228', 'If people from Poland are called "Poles", why aren\'t people from Holland called "Holes?"');

$.lang.register('randomcommand.console.loaded', 'Found $1 random command messages.');